name: Validate Last Commit

on:
  push:
    branches:
      - main # Or your release branch, e.g., 'develop'

jobs:
  validate_last_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Fetch only the last commit to reduce clone time,
          # but fetch enough to get the actual commit message.
          # A depth of 1 is usually sufficient for checking the latest commit.
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Or your preferred Node.js version
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Get Last Commit Message
        id: get_message
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=%B ${{ github.sha }})
          DELIMITER="GH_ACTION_COMMIT_MESSAGE_END_$(date +%s%N)" 
          echo "COMMIT_MESSAGE<<$DELIMETER" >> $GITHUB_OUTPUT
          echo "$COMMIT_MESSAGE" >> $GITHUB_OUTPUT
          echo "$DELIMITER" >> $GITHUB_OUTPUT

      - name: Validate Last Commit Message
        run: |
          echo "${{ steps.get_message.outputs.COMMIT_MESSAGE }}" | npx commitlint --verbose