name: Release

on:
  push:
    branches:
      - main
      - maintenance-v1

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        id: semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Output New Version
        run: |
          echo "new_release_published=${{ steps.semantic-release.outputs.new_release_published }}" >> "$GITHUB_OUTPUT"
          echo "new_version=${{ steps.semantic-release.outputs.new_release_version }}" >> "$GITHUB_OUTPUT"

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: release
    if: ${{ needs.release.outputs.new_release_published }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log release version
        run: |
          echo "New release version: ${{ needs.release.outputs.new_version }}"