name: Release

on:
  push:
    branches:
      - main
      - maintenance-v1

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    outputs:
      new_release_published: ${{ steps.semantic-release.outputs.new_release_published }}
      new_version: ${{ steps.semantic-release.outputs.new_release_version }}
      new_release_major_version: ${{ steps.semantic-release.outputs.new_release_major_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        id: semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: release
    if: ${{ needs.release.outputs.new_release_published }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log release version
        run: |
          echo "New release version: ${{ needs.release.outputs.new_version }}"


      - name: Deploy to latest alias
        run: |
          echo "Deploying to /latest"

      - name: Deploy to major version alias
        run: |
          echo "Deploying to /v${{ needs.release.outputs.new_release_major_version }}"

      - name: Deploy to specific version alias
        run: |
          echo "Deploying to /v${{ needs.release.outputs.new_version }}"